export const listaQuimicos = [
	{ id: 1, nombre: "Acevedo Albor Valeria Delaney" },
	{ id: 2, nombre: "Alvarado Madrigal Mariam Daniela" },
	{ id: 3, nombre: "Anguiano Tapia Imanol" },
	{ id: 41, nombre: "Béjar Tapia Mariana Yadira" },
	{ id: 4, nombre: "Campos Hernández Amayrani" },
	{ id: 5, nombre: "Chávez Urrutia Jared Israel" },
	{ id: 37, nombre: "Chávez Vázquez Juan Manuel" },
	{ id: 36, nombre: "Córdoba Magaña Miguel Ángel" },
	{ id: 6, nombre: "Flores Cárdenas Adriana" },
	{ id: 7, nombre: "Florian Rodríguez Ulises" },
	{ id: 38, nombre: "García Aguirre Cecilia" },
	{ id: 8, nombre: "García Bedolla Juan Daniel" },
	{ id: 9, nombre: "García Gómez Merari" },
	{ id: 10, nombre: "Gómez González Paloma Jamilet" },
	{ id: 11, nombre: "González Sánchez Zuleyma" },
	{ id: 12, nombre: "Guzmán Villalobos Jocelin Ariadne" },
	{ id: 13, nombre: "Hernández Pérez Angel de Abril" },
	{ id: 14, nombre: "Huante Díaz Francisco Javier" },
	{ id: 15, nombre: "Juárez Flores Andrea" },
	{ id: 16, nombre: "Landa Loya Siomara Inés" },
	{ id: 17, nombre: "Linares Aguilar Orlando Daniel" },
	{ id: 18, nombre: "Magaña Magaña Kayla" },
	{ id: 19, nombre: "Montaño Valdez Porfirio" },
	{ id: 39, nombre: "Mora Mendez Ramiro" },
	{ id: 20, nombre: "Ocegueda González Samara" },
	{ id: 21, nombre: "Ortiz Tapia José Francisco" },
	{ id: 22, nombre: "Peña Nuñez Julio Cesar" },
	{ id: 23, nombre: "Pineda Cazares Ronald" },
	{ id: 24, nombre: "Rangel Mejía Tatiana" },
	{ id: 25, nombre: "Reza Moreno Valeria Belen" },
	{ id: 26, nombre: "Rodríguez González Víctor Antonio" },
	{ id: 34, nombre: "Rosas Robles Fátima" },
	{ id: 35, nombre: "Sevilla Vázquez Esmeralda" },
	{ id: 40, nombre: "Silva Hernández Leidy Vanesa" },
	{ id: 27, nombre: "Tapia Muñoz Mauricio Iván" },
	{ id: 28, nombre: "Tapia Vargas Jovana Chantal" },
	{ id: 29, nombre: "Tenorio Gutiérrez Dulce Yolanda" },
	{ id: 30, nombre: "Torres Valdez Jennifer" },
	{ id: 31, nombre: "Valdovinos Salguero Devany" },
	{ id: 32, nombre: "Vázquez Pérez Itzel del Milagro" },
	{ id: 33, nombre: "Villegas Zuñiga Felipe Eduardo" },
];
